cognitedata/bazel-snapshots

examples/use-binaries/WORKSPACE
repo.bzl

See examples/use-binaries:
```
snapshots_repos(
)
```

Allow users to override URLs for downloading binaries

---

.github/workflows/ci.yaml

By default, the 'opened', 'synchronize' and 'reopened' activities trigger the 'pull_request' event.

Run CI workflow on pull_request.

---

.github/renovate.json5
renovate.json

This does a few things:
- Move renovate.json to .github/ for a cleaner project root
- Change renovate.json to renovate.json5, to support json with comments
- Set autoMerge for digest, pin and patch versions (i.e. not minor and major for now)
- Automatically run gazelle-update-repos after bazel updates

Basic Renovate configuration

---

repo.bzl

Fixes #57 
Exposing the binary with `exports_files` gave some troubles when using `change_tracker`. Exposing through a `filegroup` fixes the issue.

Export snapshots binary through a filegroup

---

examples/change-tracker/BUILD.bazel
snapshots/snapshots.bzl

Fixes #60 
* Allow `change_tracker` to track source files by setting `allow_files`
* Modify change tracker example to show how this works

Allow change_tracker to track source files

---

snapshots/go/cmd/snapshots/diff.go

The only usecases we have so far use JSON as output, which is also
much more versatile, as it outputs the tags, the kind of change, etc.
Flipping the flag, so that JSON becomes the default, and users wanting
just the plain labels can use `--format=label".
Affects #65

Set 'json' as default output format for the diff command

---

README.md
snapshots/go/cmd/snapshots/config.go
snapshots/go/cmd/snapshots/get.go
snapshots/go/cmd/snapshots/push.go
snapshots/go/cmd/snapshots/tag.go
snapshots/snapshots.bzl

Let users control the full path in the storage instead of magically
using the workspace name. The path inside the bucket can be controlled
through the 'storage' attribute.
Example:
```skylark
snapshots(
name = "snapshots",
storage = "gcs://some-bucket/my-workspace/?credential=env&project_id=env",
)
```
BREAKING CHANGES:
* no longer automatically sets path in remote storage
Fixes #66

Remove workspace name setting

---

README.md
snapshots/go/pkg/storage/storage.go

If not otherwise specified, set the value of `credential` and
`project_id` to be `env` for GCS.

Set 'env' values in storage query values by default

---

snapshots/go/cmd/snapshots/collect.go
snapshots/go/cmd/snapshots/config.go
snapshots/go/cmd/snapshots/diff.go
snapshots/go/cmd/snapshots/digest.go
snapshots/go/cmd/snapshots/get.go
snapshots/go/cmd/snapshots/push.go
snapshots/go/cmd/snapshots/tag.go
snapshots/go/pkg/bazel/bazel.go
snapshots/go/pkg/collecter/collecter.go
snapshots/go/pkg/differ/differ.go
snapshots/go/pkg/digester/digester.go
snapshots/go/pkg/getter/getter.go
snapshots/go/pkg/pusher/pusher.go
snapshots/go/pkg/tagger/tagger.go

To make number of arguments to helper methods more manageable, and maybe start to do something with optional arguments.
Also adds a bazelrc flag. If no bazelrc path is provided, no flag is passed to bazel

Add arg structs 

---

snapshots/go/cmd/snapshots/BUILD.bazel
snapshots/go/cmd/snapshots/collect.go
snapshots/go/cmd/snapshots/diff.go
snapshots/go/pkg/bazel/BUILD.bazel
snapshots/go/pkg/bazel/cache.go
snapshots/go/pkg/bazel/cache_test.go
snapshots/go/pkg/bazel/grpc_client.go
snapshots/go/pkg/bazel/grpc_client_test.go
snapshots/go/pkg/collecter/BUILD.bazel
snapshots/go/pkg/collecter/collecter.go
snapshots/go/pkg/differ/differ.go

Adds a flag to collect and diff that makes it possible to pass metadata (i.e. headers) to the Bazel cache gRPC client.
Refactors cache by moving gRPC client logic.
Still having some issues with reading from cache after remote execution. Getting NotFound errors when trying to pull from the BuildBuddy cache. However, we're successfully connecting to the cache now, and our existing (non-remote execution, but with remote cache) workflow still works as before, so I think this is still an improvement, as the gRPC code is cleaner than before.

Refactor cache/grpc client

---

deps.bzl
snapshots/snapshots.bzl

We noticed that the blobsum of some images created by some types of rules does not change. Using the manifest digest as the tracker by default fixes this. We fall back to blobsum if manifest digest isn't provided.

Use manifest_digest for tracking docker images

---

snapshots/snapshots.bzl

`--incompatible_disable_starlark_host_transitions` will become default with bazel 7.0
This makes `cfg = "host"` syntax illegal
Thread: https://github.com/bazelbuild/bazel/issues/17032

become compatible with incompatible_disable_starlark_host_transitions

---

WORKSPACE
snapshots/BUILD.bazel

Making the file public allows others to generate docs that depend on this file.

Export bzl file for stardoc support

---

snapshots/go/cmd/snapshots/collect.go
snapshots/go/cmd/snapshots/diff.go
snapshots/go/pkg/cache/BUILD.bazel
snapshots/go/pkg/cache/cache.go
snapshots/go/pkg/cache/credential_helper.go
snapshots/go/pkg/cache/grpc_client.go
snapshots/go/pkg/cache/grpc_client_test.go
snapshots/go/pkg/collecter/collecter.go
snapshots/go/pkg/differ/differ.go

Bazel has added a `--credential-helper=<pattern>=<path>` flag, where the credential helper at `<path>` will be called before connecting to a remote address matching `<pattern>`. This isn't quite that fancy, but lets users pass a single credential helper which will be used for all paths, and gives us a starting point to iterate.
The helper returns a json structure containing headers which are passed along when we connect to a remote cache, in the exact same format as the helpers passed to bazel, allowing us to use the same helper in both places.
The design doc for credential helpers in bazel provides useful background: https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md

First stab at supporting a credential helper

---

snapshots/go/cmd/snapshots/collect.go
snapshots/go/cmd/snapshots/diff.go
snapshots/go/pkg/cache/BUILD.bazel
snapshots/go/pkg/cache/cache.go
snapshots/go/pkg/cache/credential_helper.go
snapshots/go/pkg/cache/grpc_client.go
snapshots/go/pkg/cache/grpc_client_test.go
snapshots/go/pkg/collecter/BUILD.bazel
snapshots/go/pkg/collecter/collecter.go
snapshots/go/pkg/collecter/credential_helper.go
snapshots/go/pkg/differ/differ.go

Saw crashes without this check. We should probably improve our test coverage.

Verify that credential helper path is non-empty before invoking

---

.bazelrc
MODULE.bazel

This ensures that dependencies that we import are available downstream

Use rules_go go_deps to import go dependencies

---

tools/release.sh

These files are needed for consumers of this repository to import it in their MODULE.bazel

Add MODULE.bazel and WORKSPACE.bzlmod to release archive

---

MODULE.bazel
snapshots/extensions.bzl

All direct dependencies are already loaded through go.mod in MODULE.bazel. As such it is not needed, or desired, to also load the legacy go_dependencies() macro in our bzlmod extension. Furthermore, doing so causes errors for consumers of this module in some situations.

Do not load go_dependencies() in bzlmod extension

---

snapshots/go/cmd/snapshots/diff.go
snapshots/go/cmd/snapshots/push.go
snapshots/go/pkg/cache/cache.go
snapshots/go/pkg/digester/digester.go
snapshots/go/pkg/getter/getter.go

"io/ioutil" has been deprecated since Go 1.19.
Switch to "os" and "io" variants of the same functions.

all: drop use of io/ioutil

---

snapshots/go/pkg/bazel/BUILD.bazel
snapshots/go/pkg/bazel/bazel.go
snapshots/go/pkg/bazel/bazel_test.go
snapshots/go/pkg/collecter/collecter.go

Instead of buffering all build events in memory
stream them with an iterator (new in Go 1.23).
This should reduce memory pressure in really large builds
where there are lots of build events and we only care about a handful.
(Also fixes a leaking file descriptor in Collector.Collect.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cognitedata/bazel-snapshots/280)

bazel: Don't buffer build events in memory

---

MODULE.bazel

Despite documentation for rules_go stating that the module
will use the latest Go version by default ([ref](https://github.com/bazel-contrib/rules_go/blob/master/docs/go/core/bzlmod.md#go-sdks))
that appears to not be the case:
```
❯ bazel run @io_bazel_rules_go//go -- version
go version go1.23.6 darwin/arm64
```
This change configures it explicitly to use the Go version
specified in the `go.mod` file.
Verification:
```
❯ bazel run @io_bazel_rules_go//go -- version
go version go1.24.5 darwin/arm64
```

MODULE.bazel: Use Go version from go.mod

---

.github/scripts/import_snippets.sh
BUILD.bazel
README.md
tests/BUILD.bazel
tests/import_snippets_test.go

In the import snippet for published releases,
generate an SRI hash instead of a SHA256 hash.
Snippet for generating the SRI hash copied from
https://github.com/bazelbuild/bazel/issues/17124.
Resolves #240

ci/release: Provide subresource integrity snippet

---

snapshots/go/cmd/snapshots/diff.go

`snapshots diff -h` reports usage as just `diff`,
except the snapshot names and output format are not optional.
This changes the usage to clarify what's required.
Related:
It's strange for format to be required.
We can make it optional if y'all have a preferred default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cognitedata/bazel-snapshots/293)

chore(diff): improve -h output

---

snapshots/private/runner.tmpl.sh

If a snapshot_url is specified in the configuration,
`bazel run //:snapshots -- --help/-h` stop working.
```
❯ bazel run //:snapshots -- -h
INFO: Analyzed target //:snapshots (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:snapshots up-to-date:
bazel-bin/snapshots-runner.bash
bazel-bin/snapshots
INFO: Elapsed time: 0.118s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/snapshots <args omitted>
Error: unknown command "s3://my-bucket/my-workspace" for "snapshots"
Run 'snapshots --help' for usage.
snapshots: unknown command "s3://my-bucket/my-workspace" for "snapshots"
```
This fixes the issue by treating the first argument as a command
only if it does not start with a …

fix(runner.tmpl.sh): allow -h when snapshot-url is specified

---

MODULE.bazel
go.mod
go.sum
snapshots/go/cmd/snapshots/push.go
snapshots/go/pkg/getter/getter.go
snapshots/go/pkg/pusher/BUILD.bazel
snapshots/go/pkg/pusher/pusher.go
snapshots/go/pkg/storage/BUILD.bazel
snapshots/go/pkg/storage/storage.go
snapshots/go/pkg/storage/storage_test.go
snapshots/go/pkg/tagger/BUILD.bazel
snapshots/go/pkg/tagger/tagger.go

This change refactors the storage layer
to create a custom Storage abstraction around beyondstorage.
I recognize that this is an abstraction around an abstraction,
but this has a couple benefits:
- It makes the contract between bazel-snapshots and storage much clearer,
e.g. this is the exact functionality we need.
- From a code hygiene perspective,
this gives us clearer ownership of our storage layer
versus relying on beyondstorage's APIs in business logic.
- It makes it easier to swap in gocloud.dev without modifying anything else.
(Change incoming after this PR.)
In writing tests for this layer,
I discovered that beyondstorage's filesystem-backed implementation
of Storage.List does not support prefix matching:
`List(foo)` does not return `foobar`, only contents of directory `foo`.
So …

refac(storage): Create our own storage abstraction

---

snapshots/go/cmd/snapshots/BUILD.bazel
snapshots/go/cmd/snapshots/tag.go
snapshots/go/pkg/tagger/BUILD.bazel
snapshots/go/pkg/tagger/tagger.go
snapshots/go/pkg/tagger/tagger_test.go

Change the tagger implementation to accept a storage interface,
allowing for easier testing with a fake storage implementation.
The command implementation is now responsible for
injecting the storage client into the tagger.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cognitedata/bazel-snapshots/300)

refac(tagger): decouple from storage implementation

---

snapshots/go/cmd/snapshots/push.go
snapshots/go/pkg/pusher/BUILD.bazel
snapshots/go/pkg/pusher/pusher.go
snapshots/go/pkg/pusher/pusher_test.go

Change the pusher to accept a storage interface,
allowing for easier testing with a fake storage implementation.
The command implementation is now responsible for
injecting the storage client into the pusher.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cognitedata/bazel-snapshots/301)

refac(pusher): decouple from storage implementation

---

snapshots/go/cmd/snapshots/diff.go
snapshots/go/cmd/snapshots/get.go
snapshots/go/pkg/getter/BUILD.bazel
snapshots/go/pkg/getter/getter.go
snapshots/go/pkg/getter/getter_test.go

Change the getter implementation to accept a storage interface,
allowing for easier testing with a fake storage implementation.
The command implementation is now responsible for
injecting the storage client into the tagger.
As a result of this, the "diff" command also just instantiates
the client just once instead of for each snapshot resolution.
Similar to prior refactors (#301, #300).

refac(getter): decouple from storage implementation

---

.bazelrc
snapshots/go/pkg/bazel/buildevents.go
snapshots/go/pkg/collecter/BUILD.bazel
snapshots/go/pkg/collecter/collecter.go
snapshots/go/pkg/collecter/collecter_test.go

`--legacy_important_outputs` is deprecated.
Instead, Bazel exposes the NamedSetOfFiles event.
Details are available at
https://bazel.build/remote/bep-examples#consuming-namedsetoffiles
but in short:
- BEP includes NamedSetOfFiles events as the build progresses.
Each NamedSetOfFiles has a unique ID.
- TargetCompleted events reference NamedSetOfFiles by ID.
- NamedSetOfFiles events may reference other NamedSetOfFiles.
- It is guaranteed that a NamedSetOfFiles event will come before
any TargetCompleted or NamedSetOfFiles event that references it.
So the logic for traversing them is:
buffer NamedSetOfFiles events in memory,
and search through them when we see a TargetCompleted event.
Testing:
Besides included tests, I pulled this into a local Bazel workspace
with `local_path_override`,
and …

Drop need of --legacy_important_outputs

---

.github/workflows/ci.yaml

After merging this we can enable the merge queue in the branch protection settings.

Prepare CI action for merge queue
